language: python

dist: xenial

matrix:
  include:
    - python: 3.5
      env: TOX_ENV='flake8'
    - python: 3.5
      env: TOX_ENV='isort'
    - python: 3.5
      env: TOX_ENV='frontend'
    # Django 2.2
    - python: 3.5
      env: DJANGO='dj22' CMS='cms37'
    - python: 3.6
      env: DJANGO='dj22' CMS='cms37'
    - python: 3.7
      env: DJANGO='dj22' CMS='cms37'
    - python: 3.8
      env: DJANGO='dj22' CMS='cms37'
    # Django 3.0, always run the lowest supported version
    - python: 3.6
      env: DJANGO='dj30' CMS='cms37'
    # Django 3.1, always run the lowest supported version
    - python: 3.6
      env: DJANGO='dj31' CMS='cms38'
  allow_failures:
    - python: 3.6
      env: DJANGO='dj31' CMS='cms38'

install:
  - pip install coverage isort tox
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PY_VER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PY_VER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PY_VER=py37; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PY_VER=py38; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO-$CMS; fi"

before_script:
  - if [ $TOX_ENV == 'frontend' ]; then
    nvm install 8.10.0 && nvm use 8.10.0;
    npm config set spin false;
    npm install -g npm;
    npm ci;
    fi

script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)
